server:
  host:
  port: 8062

endpoints:
  - path: /ping
    method: # any method
    results:
      - when:
        response:
          returnObject:
            message: "pong"
  - path: /
    method: "GET"
    results:
      - when:
          query:
            time: 10
            age: 30
        response:
          returnCode: 200
          returnObject:
            - "item 1"
            - "item 2"
      - response: # no condition == default return
          returnCode: 200
          returnObject:
            data1: this is data1
            data2: this is data2
      - when:  # Same as above, but it's nerver reach here because the above item matched
        response: # no condition == default return
          returnCode: 200
          returnObject:
            data1: this is data1
            data2: this is data2
  - path: /
    method: "POST"
    results:
      - when:
          payload:
            password: "a too simple password"
            address:
              primary: "France"
        response:
          returnCode: 400
          returnObject: BAD REQUEST
      - when: # in any case
        response:
          returnCode: 500
          returnObject: 
    

